### ISSUE TITLE
[Requirements] Need module pseudohex.pseudohex

### ISSUE THREAD

**Issue by LeamHall** [egor045/T5_worldgen#1]
Base: CentOS 6, system python 2.6.6

 ./generate_sample_data.py 
Traceback (most recent call last):
  File "./generate_sample_data.py", line 7, in <module>
    from T5_worldgen.system import System
  File "/home/leam/lang/git/others/T5_worldgen/T5_worldgen/system.py", line 6, in <module>
    from T5_worldgen.planet import Planet
  File "/home/leam/lang/git/others/T5_worldgen/T5_worldgen/planet.py", line 5, in <module>
    import T5_worldgen.upp as uwp
  File "/home/leam/lang/git/others/T5_worldgen/T5_worldgen/upp.py", line 5, in <module>
    from pseudohex.pseudohex import Pseudohex
ImportError: No module named pseudohex.pseudohex

**Comment by egor045** [comment]
Fixed - pseudohex included. Unit tests pass. I'll hold this open until I get confirmation

**Comment by LeamHall** [comment]
1. pseudohex works. Here's the tail of an output:

```
System-3892,X,6,5,A,9,E,G,6,X65A9EG-6
System-3893,C,6,3,4,8,5,5,8,C634855-8
System-3894,X,4,3,3,6,7,8,1,X433678-1
System-3895,D,4,4,2,6,6,B,6,D44266B-6
System-3896,C,5,2,0,3,2,0,A,C520320-A
System-3897,X,4,2,6,6,4,3,0,X426643-0
System-3898,C,8,9,7,7,7,9,7,C897779-7
System-3899,B,7,9,8,7,9,D,8,B79879D-8
```

However, STDOUT seems to also put stuff out:

```
3891 T5_worldgen.system _calculate_infrastructure(): Ni => infrastructure = 1D6 + Ix
3892 T5_worldgen.system __init__(): args to EconomicExtension
3892 T5_worldgen.system __init__(): pbg = 201 pop = 0 tl = 9 Ix = -2
3892 T5_worldgen.system __init__(): trade codes = Va Tz
3892 T5_worldgen.system __init__(): args to EconomicExtension
3892 T5_worldgen.system __init__(): pbg = 402 pop = 5 tl = 1 Ix = -3
3892 T5_worldgen.system __init__(): trade codes = He Ni Po Tz
3892 T5_worldgen.system _calculate_infrastructure(): Ni => infrastructure = 1D6 + Ix
3893 T5_worldgen.system __init__(): args to EconomicExtension
3893 T5_worldgen.system __init__(): pbg = 802 pop = 8 tl = 5 Ix = 0
3893 T5_worldgen.system __init__(): trade codes = Ph Pa Ri
3894 T5_worldgen.system __init__(): args to EconomicExtension
3894 T5_worldgen.system __init__(): pbg = 202 pop = 2 tl = 9 Ix = -1
3894 T5_worldgen.system __init__(): trade codes = Lo
3894 T5_worldgen.system _calculate_infrastructure(): Lo => infrastructure = 1
3894 T5_worldgen.system __init__(): args to EconomicExtension
3894 T5_worldgen.system __init__(): pbg = 703 pop = 7 tl = 12 Ix = 3
3895 T5_worldgen.system __init__(): trade codes = Wa Ri Ho
```

**Comment by LeamHall** [comment]
2. Note that the '{:04d}'format(int) on line 11 of generate_sample_data.py was introduced in python 2.7. So the script will fail in 2.6 and earlier.

3. Still hitting print issues in Python 3.x.

**Comment by egor045** [comment]
stdout fixed - a couple of modules had logging set to DEBUG. I'll take a look at the python 3 print issues.

**Comment by LeamHall** [comment]
Have you pushed the changes up? Still getting the debug.

**Comment by egor045** [comment]
I've set logging levels to ERROR throughout. generate_sample_data.py just shows sample data, no logging output.You'll see funky output if you run the unit tests, but I don't plan to fix those - the unit tests all pass.

Latest commit (which has not debugging output when I run generate_sample_data) is https://github.com/egor045/T5_worldgen/commit/7573916c7928b60bf86bfaccb3ae498629f95008

**Comment by LeamHall** [comment]
That works. Careful with your merge; you made the 7573916 changes on the master branch.

**Comment by egor045** [comment]
Python 3 print issues should be resolved, likewise Python 2.6 (although I don't have a 2.6 installation to test against). If you've no objections, I'll close this issue.

Thanks for taking the time to cast an eye over the code - I appreciate it.

**Comment by LeamHall** [comment]
Works for me. I have 2.6.6 and 3.4 on a laptop and don't mind testing for you. Also, signed up for a free on-line Python class to boost my meager skills.  :)

**Comment by egor045** [comment]
Looks like we're all good here. Closing.
